### ISSUE TITLE
Import error : cannot import name 'TriMesh' from 'matplotlib.tri'

### ISSUE THREAD

**Issue by yun881201** [raphaelquast/EOmaps#111]
When I import EOmaps, I obtain the following import error

ImportError                               Traceback (most recent call last)
Input In [9], in <cell line: 1>()
----> 1 import eomaps

File ~\anaconda3\envs\specavail1\lib\site-packages\eomaps\__init__.py:1, in <module>
----> 1 from .eomaps import Maps, MapsGrid
      2 from ._version import __version__
      4 __author__ = "Raphael Quast"

File ~\anaconda3\envs\specavail1\lib\site-packages\eomaps\eomaps.py:112, in <module>
    102 from cartopy import crs as ccrs
    104 from .helpers import (
    105     pairwise,
    106     cmap_alpha,
   (...)
    110     searchtree,
    111 )
--> 112 from ._shapes import shapes
    114 from ._containers import (
    115     data_specs,
    116     map_objects,
   (...)
    120     NaturalEarth_features,
    121 )
    123 from ._cb_container import cb_container

File ~\anaconda3\envs\specavail1\lib\site-packages\eomaps\_shapes.py:2, in <module>
      1 from matplotlib.collections import PolyCollection, QuadMesh
----> 2 from matplotlib.tri import TriMesh, Triangulation
      3 import numpy as np
      5 from pyproj import CRS, Transformer

ImportError: cannot import name 'TriMesh' from 'matplotlib.tri' (C:\Users\user\anaconda3\envs\specavail1\lib\site-packages\matplotlib\tri\__init__.py)

<details>
<summary> My conda list: </summary>

# packages in environment at C:\Users\user\anaconda3\envs\specavail1:
Note: you may need to restart the kernel to use updated packages.

#
# Name                    Version                   Build  Channel
argon2-cffi               21.3.0             pyhd3eb1b0_0  
argon2-cffi-bindings      21.2.0          py310h2bbff1b_0  
asttokens                 2.0.5              pyhd3eb1b0_0  
attrs                     22.1.0                   pypi_0    pypi
backcall                  0.2.0              pyhd3eb1b0_0  
beautifulsoup4            4.11.1          py310haa95532_0  
bleach                    4.1.0              pyhd3eb1b0_0  
blosc                     1.21.1               h74325e0_3    conda-forge
boost-cpp                 1.78.0               h9f4b32c_1    conda-forge
branca                    0.5.0              pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                h8ffe710_7    conda-forge
brotli-bin                1.0.9                h8ffe710_7    conda-forge
brotlipy                  0.7.0           py310he2412df_1004    conda-forge
bzip2                     1.0.8                he774522_0  
ca-certificates           2022.9.14            h5b45459_0    conda-forge
cairo                     1.16.0            hd694305_1014    conda-forge
cairocffi                 1.3.0              pyhd8ed1ab_0    conda-forge
cairosvg                  2.5.2              pyhd8ed1ab_0    conda-forge
cartopy                   0.21.0          py310h05326cb_0    conda-forge
certifi                   2022.9.14          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310h2bbff1b_0  
cfitsio                   4.1.0                h5a969a9_0    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
click                     8.1.3           py310h5588dad_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.2              pyhd8ed1ab_1    conda-forge
cloudpickle               2.2.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.5           py310haa95532_0  
colorcet                  3.0.0              pyhd8ed1ab_0    conda-forge
contourpy                 1.0.5           py310h232114e_0    conda-forge
cryptography              37.0.4          py310ha857299_0    conda-forge
cssselect2                0.2.1              pyh9f0ad1d_1    conda-forge
curl                      7.83.1               h789b8ee_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
dask-core                 2022.9.1           pyhd8ed1ab_0    conda-forge
datashader                0.14.2             pyh6c4a22f_0    conda-forge
datashape                 0.5.4                      py_1    conda-forge
debugpy                   1.5.1           py310hd77b12b_0  
decorator                 5.1.1              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
descartes                 1.1.0                      py_4    conda-forge
docopt                    0.6.2                    pypi_0    pypi
entrypoints               0.4             py310haa95532_0  
eomaps                    4.4.2              pyhd8ed1ab_0    conda-forge
executing                 0.8.3              pyhd3eb1b0_0  
expat                     2.4.9                h1537add_0    conda-forge
fiona                     1.8.21                   pypi_0    pypi
flask                     2.2.2                    pypi_0    pypi
folium                    0.12.1.post1       pyhd8ed1ab_1    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.0               hce3cb01_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.37.3          py310h8d17308_0    conda-forge
freetype                  2.12.1               h546665d_0    conda-forge
freexl                    1.0.6                ha8e266a_0    conda-forge
fsspec                    2022.8.2           pyhd8ed1ab_0    conda-forge
gdal                      3.4.3                    pypi_0    pypi
geopandas                 0.11.1             pyhd8ed1ab_0    conda-forge
geopandas-base            0.11.1             pyha770c72_0    conda-forge
geos                      0.2.3                    pypi_0    pypi
geotiff                   1.7.1                h714bc5f_3    conda-forge
gettext                   0.19.8.1          ha2e2712_1008    conda-forge
hdf4                      4.2.15               h0e5069d_4    conda-forge
hdf5                      1.12.2          nompi_h2a0e4a3_100    conda-forge
icu                       70.1                 h0e60522_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
intel-openmp              2022.1.0          h57928b3_3787    conda-forge
ipykernel                 6.15.2          py310haa95532_0  
ipython                   8.4.0           py310haa95532_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
itsdangerous              2.1.2                    pypi_0    pypi
jedi                      0.18.1          py310haa95532_1  
jinja2                    3.1.2                    pypi_0    pypi
joblib                    1.2.0              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h8ffe710_2    conda-forge
js2py                     0.71                     pypi_0    pypi
jsonschema                4.4.0           py310haa95532_0  
jupyter_client            7.3.5           py310haa95532_0  
jupyter_core              4.10.0          py310haa95532_0  
jupyterlab_pygments       0.1.2                      py_0  
kealib                    1.4.15               hdf81f3a_1    conda-forge
kiwisolver                1.4.4           py310h476a331_0    conda-forge
krb5                      1.19.3               h1176d77_0    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libblas                   3.9.0              16_win64_mkl    conda-forge
libbrotlicommon           1.0.9                h8ffe710_7    conda-forge
libbrotlidec              1.0.9                h8ffe710_7    conda-forge
libbrotlienc              1.0.9                h8ffe710_7    conda-forge
libcblas                  3.9.0              16_win64_mkl    conda-forge
libcurl                   7.83.1               h789b8ee_0    conda-forge
libdeflate                1.13                 h8ffe710_0    conda-forge
libffi                    3.4.2                hd77b12b_4  
libgdal                   3.5.2                hc386656_1    conda-forge
libglib                   2.72.1               h3be07f2_0    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
libkml                    1.3.0             hf2ab4e4_1015    conda-forge
liblapack                 3.9.0              16_win64_mkl    conda-forge
libnetcdf                 4.8.1           nompi_h85765be_104    conda-forge
libpng                    1.6.38               h19919ed_0    conda-forge
libpq                     14.5                 hfcc5ef8_0    conda-forge
librttopo                 1.1.0               h2842628_11    conda-forge
libsodium                 1.0.18               h62dcd97_0  
libspatialindex           1.9.3                h39d44d4_4    conda-forge
libspatialite             5.0.1               ha17912d_18    conda-forge
libsqlite                 3.39.3               hcfcfb64_0    conda-forge
libssh2                   1.10.0               h680486a_3    conda-forge
libtiff                   4.4.0                h92677e6_3    conda-forge
libwebp-base              1.2.4                h8ffe710_0    conda-forge
libxcb                    1.13              hcd874cb_1004    conda-forge
libxml2                   2.9.14               hf5bbc77_4    conda-forge
libzip                    1.9.2                hfed4ece_1    conda-forge
libzlib                   1.2.12               hcfcfb64_3    conda-forge
llvmlite                  0.38.1          py310h2c03ce5_0    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lxml                      4.9.1                    pypi_0    pypi
lz4-c                     1.9.3                h8ffe710_1    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
mapclassify               2.4.3              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.1           py310h2bbff1b_0  
matplotlib-base           3.6.0           py310h51140c5_0    conda-forge
matplotlib-inline         0.1.6           py310haa95532_0  
mistune                   0.8.4           py310h2bbff1b_1000  
mkl                       2022.1.0           h6a75c08_874    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
munch                     2.5.0                      py_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
nbclient                  0.5.13          py310haa95532_0  
nbconvert                 6.4.4           py310haa95532_0  
nbformat                  5.5.0           py310haa95532_0  
nest-asyncio              1.5.5           py310haa95532_0  
networkx                  2.8.6              pyhd8ed1ab_0    conda-forge
notebook                  6.4.12          py310haa95532_0  
numba                     0.55.2          py310h77579ad_0    conda-forge
numpy                     1.22.4+vanilla           pypi_0    pypi
openjpeg                  2.5.0                hc9384bd_1    conda-forge
openssl                   1.1.1q               h8ffe710_0    conda-forge
owslib                    0.27.2             pyhd8ed1ab_1    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.3                    pypi_0    pypi
pandocfilters             1.5.0              pyhd3eb1b0_0  
param                     1.12.2             pyh6c4a22f_0    conda-forge
parso                     0.8.3              pyhd3eb1b0_0  
partd                     1.3.0              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 h0e60522_0    conda-forge
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    9.2.0           py310h52929f7_2    conda-forge
pip                       22.1.2          py310haa95532_0  
pipwin                    0.5.2                    pypi_0    pypi
pixman                    0.40.0               h8ffe710_0    conda-forge
poppler                   22.04.0              hb57f792_3    conda-forge
poppler-data              0.4.11               hd8ed1ab_0    conda-forge
postgresql                14.5                 h1c22c4f_0    conda-forge
proj                      9.0.1                h1cfcee9_1    conda-forge
prometheus_client         0.14.1          py310haa95532_0  
prompt-toolkit            3.0.20             pyhd3eb1b0_0  
psutil                    5.9.0           py310h2bbff1b_0  
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pure_eval                 0.2.2              pyhd3eb1b0_0  
pycparser                 2.21               pyhd3eb1b0_0  
pyct                      0.4.6                      py_0    conda-forge
pyct-core                 0.4.6                      py_0    conda-forge
pyepsg                    0.4.0                      py_0    conda-forge
pygments                  2.11.2             pyhd3eb1b0_0  
pyjsparser                2.7.1                    pypi_0    pypi
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyprind                   2.11.3                   pypi_0    pypi
pyproj                    3.4.0           py310h6377384_0    conda-forge
pyrsistent                0.18.0          py310h2bbff1b_0  
pyshp                     2.3.1              pyhd8ed1ab_0    conda-forge
pysmartdl                 1.3.4                    pypi_0    pypi
pysocks                   1.7.1              pyh0701188_6    conda-forge
python                    3.10.4               hbb2ffb3_0  
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.16.2          py310haa95532_0  
python_abi                3.10                    2_cp310    conda-forge
pytz                      2022.2.1           pyhd8ed1ab_0    conda-forge
pytz-deprecation-shim     0.1.0.post0              pypi_0    pypi
pywin32                   302             py310h2bbff1b_2  
pywinpty                  2.0.2           py310h5da7b33_0  
pyyaml                    6.0             py310he2412df_4    conda-forge
pyzmq                     23.2.0          py310hd77b12b_0  
requests                  2.28.1             pyhd8ed1ab_1    conda-forge
rtree                     1.0.0           py310h1cbd46b_1    conda-forge
scikit-learn              1.1.2           py310h3a564e9_0    conda-forge
scipy                     1.9.1           py310h578b7cb_0    conda-forge
send2trash                1.8.0              pyhd3eb1b0_1  
setuptools                63.4.1          py310haa95532_0  
shapely                   1.8.2                    pypi_0    pypi
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.9                h82413e6_1    conda-forge
soupsieve                 2.3.2.post1              pypi_0    pypi
sqlite                    3.39.2               h2bbff1b_0  
stack_data                0.2.0              pyhd3eb1b0_0  
tbb                       2021.5.0             h91493d7_2    conda-forge
terminado                 0.13.1          py310haa95532_0  
testpath                  0.6.0           py310haa95532_0  
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tiledb                    2.11.2               h5689973_0    conda-forge
tinycss2                  1.1.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h2bbff1b_0  
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tornado                   6.2             py310h2bbff1b_0  
traitlets                 5.1.1              pyhd3eb1b0_0  
trimesh                   3.15.1                   pypi_0    pypi
typing-extensions         4.3.0           py310haa95532_0  
typing_extensions         4.3.0           py310haa95532_0  
tzdata                    2022.2                   pypi_0    pypi
tzlocal                   4.2                      pypi_0    pypi
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
unicodedata2              14.0.0          py310he2412df_1    conda-forge
urllib3                   1.26.12                  pypi_0    pypi
vc                        14.2                 h21ff451_1  
vs2015_runtime            14.29.30139          h890b9b1_7    conda-forge
wcwidth                   0.2.5              pyhd3eb1b0_0  
webencodings              0.5.1           py310haa95532_1  
werkzeug                  2.2.2                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0  
win_inet_pton             1.1.0           py310h5588dad_4    conda-forge
wincertstore              0.2             py310haa95532_2  
winpty                    0.4.3                         4  
xarray                    2022.6.0           pyhd8ed1ab_1    conda-forge
xerces-c                  3.2.3                h0e60522_5    conda-forge
xmltodict                 0.13.0             pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.9                hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xyzservices               2022.9.0           pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
zeromq                    4.3.4                hd77b12b_0  
zlib                      1.2.12               h8cc25b3_3  
zstd                      1.5.2                h7755175_4    conda-forge

</details>

**Comment by yun881201** [comment]
I modified File ~\anaconda3\envs\specavail1\lib\site-packages\eomaps_shapes.py:2
like this :
original
1 from matplotlib.collections import PolyCollection, QuadMesh
2 from matplotlib.tri import TriMesh, Triangulation
modification
1 from matplotlib.collections import PolyCollection, QuadMesh, TriMesh
2 from matplotlib.tri import Triangulation

This solved the error problem.

**Comment by raphaelquast** [comment]
re-opening this since this is most probably an issue with the recent `matplotlib v3.6` release that apparently changed the import for  `TriMesh`...   I'll have to check with the matplotlib-devs if this is intended or not...

**Comment by raphaelquast** [comment]
This is now fixed in the latest hotfix-release `EOmaps v4.4.3` ... thanks again for reporting!
