### ISSUE TITLE
zorder of "set_data" and "set_shape"

### ISSUE THREAD

**Issue by yun881201** [raphaelquast/EOmaps#114]
I drew my custom country map over the default map controlling zorder. But my custom country also overlapped my data.
I can't find zorder option of "set_data" and "set_shape" in EOmaps.

**Comment by raphaelquast** [comment]
The zorder (and any other property you want to pass to the artist) is set with `m.plot_map(zorder=1)`!
(see [docs](https://eomaps.readthedocs.io/en/latest/api.html#plot-the-map-and-save-it))

**Comment by raphaelquast** [comment]
I'm closing this... feel free to re-open if something is still unclear!
