### ISSUE TITLE
m.ax.add_geometries is not working

### ISSUE THREAD

**Issue by yun881201** [raphaelquast/EOmaps#152]
Hello. 

I have reconstructed my anaconda env.
Before reconstructing the env, I used code "m.ax.add_geometries~" with eomaps, which is pure cartopy code except "m.", to draw modified map. But now that code does not work. is this only my problem?

code example:
```python
import cartopy.crs as ccrs
import cartopy.feature as cf
from eomaps import Maps, MapsGrid
import cartopy.io.shapereader as shpreader

m = Maps(crs=5179)
m.ax.set_extent([124.598822,131.87222222,38.70000000,33.10000000], crs=ccrs.PlateCarree()) ## Important
m.ax.axis('off')
m.ax.add_feature(cf.OCEAN.with_scale("50m")) 
shpfilename = shpreader.natural_earth(resolution='50m', category='cultural', name='admin_0_countries')
reader = shpreader.Reader(shpfilename)
countries = reader.records()
for country in countries:
    if country.attributes['ADM0_A3'] == 'KOR':
        m.ax.add_geometries(country.geometry, ccrs.PlateCarree(), facecolor=cf.COLORS['water'], edgecolor=cf.COLORS['water'])
m.ax.add_feature(cf.BORDERS, linewidth=0.7, linestyle=':', zorder=5) # country borders in cartopy.
```

**Comment by raphaelquast** [comment]
Hello, 
This is indeed a consequence of some more fundamental changes in EOmaps v6.x since now all artists are managed explicitly.
This brings a lot of speed-up and enhancements (for multi-layering etc.) but at the moment requires all artists to be managed by EOmaps.

To re-use your code, you would need to explicitly add artists created with cartopy methods to the "blit-manager", e.g.:
```python
artist = m.ax.add_feature(cf.OCEAN.with_scale("50m")) 
m.BM.add_bg_artist(artist, layer=m.layer)      # for "background artists"
# m.BM.add_bg_artist(artist, layer=m.layer)    # for "dynamic artists"
```


However, looking at your code I'd recommend leveraging some of EOmaps capabilities as it would also greatly simplify your code...

Here's how your code would look using EOmaps only:
```python
from eomaps import Maps

m = Maps(crs=5179, frameon=False)
m.set_extent([124.598822,131.87222222,38.70000000,33.10000000], crs=4326)
m.add_feature.physical.ocean(scale=50, fc="#97b6e1")
m.add_feature.cultural.admin_0_boundary_lines_land(scale=10, fc="none", ec="k", lw=0.7, ls=":", zorder=5)

gdf = m.add_feature.cultural.admin_0_countries.get_gdf(scale=50)  # fetch GeoDataFrame for the feature
m.add_gdf(gdf[gdf.ADM0_A3 == "KOR"], facecolor="#97b6e1", edgecolor="#97b6e1")
```

**Comment by yun881201** [comment]
Thank you for your quick and detailed answer. I didn't know that updates. It's good to see the progress. I've been very busy since the end of last year until now, but if thins get better, I'll keep giving feedback for the progress of eomaps!

**Comment by raphaelquast** [comment]
Your feedback is highly appreciated! 

I realize that the current behavior with `cartopy` and `matpltoltlib` functions is suboptimal. 

There is already a fix implemented in the `dev` branch which will be merged in the next minor release of EOmaps. 
It will cause all "unmanaged" artists to appear on the `"base"` layer of the map by default .

This way they will work just fine out of the box and the workaround will only be needed in the rare cases where you want to put a cartopy-artist on a **different layer** than the `"base"` layer.
