### ISSUE TITLE
Migrate to pyproject.toml

### ISSUE THREAD

**Issue by banesullivan** [raphaelquast/EOmaps#210]
Tracking a comment from @jhkennedy in https://github.com/pyOpenSci/software-submission/issues/138#issuecomment-1858583110 here:

> It's time to move from setup.py to pyproject.toml

While `setup.py` is not technically deprecated, ref https://packaging.python.org/en/latest/discussions/setup-py-deprecated/, `pyproject.toml` is the new standardized format to describe project metadata declaratively, introduced with [PEP 621](https://peps.python.org/pep-0621/). It's easier to work with and allows for shared configuration between different tools.

**Comment by raphaelquast** [comment]
#216 is now merged into the `dev` branch!   
EOmaps v8.0 (see #205) will incorporate the following changes:
- switch from `setup.py` to `pyproject.toml`
- minimal supported python version is `v3.8`
- version is now single-sourced to `pyproject.toml` file (`_version.py` is removed)
- optional dependency groups are implemented for `pip` install

**Comment by banesullivan** [comment]
Fantastic!
