### ISSUE TITLE
MapsGrid.__getitem(...) references 'ax_...' and not 'm_...'

### ISSUE THREAD

**Issue by langdonr621** [raphaelquast/EOmaps#35]
hi Raphael,

trying the example [Data-classification and multiple Maps in one figure](https://eomaps.readthedocs.io/en/latest/EOmaps_examples.html#data-classification-and-multiple-maps-in-one-figure) w/ a pristine 2.1.1 and replacing the line
```python
mg.m_0_0.set_data_specs(data=data, xcoord="lon", ycoord="lat", in_crs=4326)
```
w/
```python
mg[0, 0].set_data_specs(data=data, xcoord="lon", ycoord="lat", in_crs=4326)
```
which i assume should work, instead raises... 
```python
Traceback (most recent call last):
  File "/opt/ws-py/eomaps2/test_grid.py", line 15, in <module>
    mg[0, 0].set_data_specs(data=data, xcoord="lon", ycoord="lat", in_crs=4326)
  File "/opt/ws-py/eomaps2/.env/lib/python3.10/site-packages/eomaps/eomaps.py", line 2042, in __getitem__
    return getattr(self, f"ax_{key[0]}_{key[1]}")
AttributeError: 'MapsGrid' object has no attribute 'ax_0_0'. Did you mean: 'm_0_0'?
```

replacing `ax` w/ `m` in line 2042 in `eomaps.py` seems to solve the problem.

also noticed that `ax_...` is still mentioned in the `MapsGrid` class documentation.

**Comment by raphaelquast** [comment]
hah, nice catch... thanks!
that is a remaining typo from the old notation I used when I introduced the MapsGrid feature.
(I definitely need to catch up writing more tests to avoid such issues in the future...)

I'll fix it right away and include it in v2.1.2!
